name = "Fruitlands"
author = "DeerLacy"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a745e7fc097e4a184ca1943ff99be21fcd0fb7552d56b96300529890842dfe5"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"

[options]
acceptable-game-versions = []
