name = "Fruitlands"
author = "DeerLacy"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7ab5347783650d3131212dbf6c982ea4a96dfdf2d481a47a981004892e74b3a"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"

[options]
acceptable-game-versions = []
