name = "Fruitlands"
author = "DeerLacy"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8cf5bfc8927e462afdd3bfda81f15c219c46baa3e52dd7d1872de70f4924035a"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"

[options]
acceptable-game-versions = []
