name = "Fruitlands"
author = "DeerLacy"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fae93a181522b6e29d82e5155b260cabe61a33e5395b03cb42f61b760ef540f7"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"

[options]
acceptable-game-versions = []
